services:
  wireproxy:
    image: "ghcr.io/whyvl/wireproxy:latest"
    volumes:
      - ./wg.conf:/wg.conf:ro
      - ./wireproxy.conf:/wireproxy.conf:ro
    command: -s -c /wireproxy.conf
    cpus: 0.1
    mem_limit: 64m
    read_only: true

  shadowsocks:
    image: "ghcr.io/shadowsocks/sslocal-rust:latest"
    volumes:
      - ./shadowsocks.json:/etc/shadowsocks-rust/config.json:ro
    cpus: 0.1
    mem_limit: 64m
    read_only: true

  alloy:
    image: "grafana/alloy:latest"
    restart: unless-stopped
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/lib/alloy/data
    cpus: 0.2
    mem_limit: 128m
    read_only: true
